# Generated by Django 5.2.7 on 2025-12-01 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sensor', '0002_delete_humiditysensor_delete_temperaturesensor_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mood',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mood_name', models.CharField(max_length=50)),
                ('reg_date', models.DateTimeField(editable=False)),
            ],
        ),
    ]
