# Generated by Django 5.2.7 on 2025-11-30 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sensor', '0002_delete_humiditysensor_delete_temperaturesensor_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ManufacturingStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ui_state', models.CharField(max_length=50)),
                ('mood_name', models.CharField(blank=True, max_length=50, null=True)),
                ('recipe_L', models.FloatField(default=0.0)),
                ('recipe_C', models.FloatField(default=0.0)),
                ('recipe_V', models.FloatField(default=0.0)),
                ('recipe_B', models.FloatField(default=0.0)),
                ('lora_state', models.CharField(blank=True, max_length=50, null=True)),
                ('reg_date', models.DateTimeField(editable=False)),
            ],
        ),
    ]
