# Generated by Django 5.2.7 on 2025-12-01 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sensor', '0003_mood'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeviceStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(default='SCREEN_START', max_length=50)),
                ('mood_code', models.CharField(default='N/A', max_length=50)),
                ('reg_date', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Device Status',
            },
        ),
        migrations.DeleteModel(
            name='Mood',
        ),
    ]
