# Generated by Django 5.2.7 on 2025-11-30 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sensor', '0003_manufacturingstatus'),
    ]

    operations = [
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ui_state', models.CharField(default='START', max_length=50)),
                ('mood_name', models.CharField(default='Ready', max_length=100)),
                ('recipe_L', models.FloatField(default=0.0)),
                ('recipe_C', models.FloatField(default=0.0)),
                ('recipe_V', models.FloatField(default=0.0)),
                ('recipe_B', models.FloatField(default=0.0)),
                ('reg_date', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-reg_date'],
            },
        ),
        migrations.DeleteModel(
            name='ManufacturingStatus',
        ),
        migrations.AlterModelOptions(
            name='proximitysensor',
            options={'ordering': ['-reg_date']},
        ),
        migrations.AlterField(
            model_name='proximitysensor',
            name='name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='proximitysensor',
            name='reg_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='proximitysensor',
            name='value',
            field=models.BooleanField(default=False),
        ),
    ]
