# Generated by Django 5.2.7 on 2025-12-01 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sensor', '0004_devicestatus_delete_mood'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='devicestatus',
            name='mood_code',
        ),
        migrations.RemoveField(
            model_name='devicestatus',
            name='status',
        ),
        migrations.AddField(
            model_name='devicestatus',
            name='c_screen_status',
            field=models.CharField(default='SCREEN_START', max_length=50, verbose_name='C Program Status'),
        ),
        migrations.AddField(
            model_name='devicestatus',
            name='is_serial_connected',
            field=models.BooleanField(default=False, verbose_name='Serial Connected'),
        ),
        migrations.AlterField(
            model_name='devicestatus',
            name='reg_date',
            field=models.DateTimeField(auto_now=True, verbose_name='Last Update Time'),
        ),
    ]
